### ISSUE TITLE
Include specification PDF?

### ISSUE THREAD

**Issue by chocol4te** [jonas-schievink/nrf51-ble-demo#9]
Including the spec PDF might be nice, plus maybe making it easier to reference pages in code comments.

**Comment by jonas-schievink** [comment]
Pretty sure that would be a copyright violation. The PDF is also pretty large (24MiB). Referencing pages is a good idea, but they are only valid for one specific version of the Bluetooth Core spec. We could reference chapters instead, but they might suffer the same problem. It would still be better than not referencing anything though.
